name: publish

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: budget-app-hunterhod
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        with:
          args: app deploy
